---
title: "About the Authors"
author: "Kay Endriss"
date: "June 13, 2015"
output: html_document
---

Information you may wish to know: our group took the Surrealist “exquisite corpse” technique and made it our own to create this story. [Wikipedia: Exquisite corpse.] (https://en.wikipedia.org/wiki/Exquisite_corpse) Each author was provided all previous content via email when it was their turn, and was expected to write their part within 2 days. One author (PJL) was in charge of coordinating the process, and he chose the ordering of authorship. Only he saw the entire story developing. We started work in early May and we had one face-to-face meeting in June to discuss the finished story together. At that meeting we agreed only minor edits were in order. A testament to the flow of this story, some authors remarked that they had difficulty deciding how long to make their contributions since it was not always obvious how many authors had written so far.

This is the first time we have done anything like this. Our group is a subset of a book club that was reading and discussing entire books, but has recently scaled back to take on articles, and sometimes short videos that we view together and then discuss. Together we study complexity theory (or systems thinking), but we often find ourselves discussing big statistical issues such as randomness—Does true randomness exist? Philosophy is central to many discussions. At our next meeting we plan to re-watch “World of Tomorrow” by Don Hertzfeldt because many of us wanted a second chance to get beyond the surface of this incredibly dense work. Most authors are in The Laboratory for Complex Brain Networks, and/or in The Department of Radiology at Wake Forest School of Medicine, Winston-Salem, North Carolina. Select outsiders have joined from Elon University, East Carolina University, Weaver Academy, and The Career Center High School. Among us there are those with the following degrees: BS, MD, MD/PhD, MEd, MS, PhD; and a couple are graduate students in pursuit of PhDs. Together we have expertise in computer science, mathematics, neuroscience, physics, psychology, radiology, and statistics.

We hope you enjoy our story.

~ Kay Endriss on behalf of all 10 authors of "The Card""
